version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
    environment:
      - DEBUG=True
    depends_on:
      - redis
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    
  # Optional: PostgreSQL instead of SQLite
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: chatapp
  #     POSTGRES_USER: chatuser
  #     POSTGRES_PASSWORD: chatpass
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: